name: Semgrep SAST Scan

on:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Run Semgrep SAST Scan
        run: semgrep scan --config auto .